<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function createPaymentForUser(User $user)
    {
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->eq('status', Payable::STATUS_AVAILABLE));

        $payables = $user->getPayables()->matching($criteria);

        $payment = new Payment();
        $payment->setUser($user);
        foreach ($payables as $payable) {
            $payment->addPayable($payable);
            $payable->setProcessing($payable->getAvailable());
            $payable->setAvailable(0);
        }

        $em = $this->getEntityManager();
        $em->persist($payment);
        $em->flush();

        return $payment;
    }
}
