<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\Common\Collections\Criteria;
/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends EntityRepository
{
    public function createPaymentForUser(User $user)
    {
        $criteria = Criteria::create();
        $criteria->where(Criteria::expr()->gt('available', 0));

        $payables = $user->getPayables()->matching($criteria);

        $payment = new Payment();
        $payment->setUser($user);
        foreach ($payables as $payable) {
            $payment->addPayable($payable);
            $payable->setProcessing($payable->getAvailable());
            $payable->setAvailable(0);
        }



          //  print_r($payable);
            //print_r($user);

        


        $em = $this->getEntityManager();
        $em->persist($payment);
        $em->flush();



        return $payment;
    }

    public function getPendingPayments()
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('p')
            ->from('App\Entity\Payment', 'p', 'p.id')
            ->where('p.status = :pending')
            ->setParameter('pending', Payment::STATUS_PENDING)
            ->getQuery()
            ->getResult();
    }
}
