<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta name="generator" content="HTML Tidy for Linux (vers 6 November 2007), see www.w3.org" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="description" content="Save money on millions of products from thousands of top online stores at BeeSavy.com with comparison shopping, cash back, and coupons." />
<title>BeeSavy – Taking the sting out of online shopping</title>
<link rel="shortcut icon" href="/images/favicon.ico" />
<link href="/styles/main.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/home.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/results.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/button.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/view.css" media="screen" rel="stylesheet" type="text/css" />
<link media="screen" rel="stylesheet" href="/styles/colorbox.css" />
<link media="screen" rel="stylesheet" href="/css/matrix_table.css" />
		<style type="text/css" title="currentStyle">
			@import "/css/matrix_table.css";
		</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js" type="text/javascript"></script>
<!-- Generated by OpenX 2.8.7 -->
<!-- <script type='text/javascript' src='http://50.16.95.24/openx/www/delivery/spcjs.php?id=1'></script>-->
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23342317-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script src="/colorbox/jquery.colorbox.js" type="text/javascript"></script>
<script type='text/javascript' src='/script_files/nav_bar.js'></script>
<script type="text/javascript" src="/zeroclipboard/ZeroClipboard.js"></script>
		<script type="text/javascript" language="javascript" src="/script_files/jquery.dataTables.js"></script>
<script type='text/javascript' src='/script_files/money.js'></script>
<script type='text/javascript'>
$(document).ready(function(){
    $(".make-home").colorbox();
        ZeroClipboard.setMoviePath('<?php echo base_url() ?>zeroclipboard/ZeroClipboard.swf');
		var clips = [];
		
		function startZC() {
            var elements = $(".couponList");
            var container = $(".couponList .click-contain");
            var buttons = $(".couponList .click-button");
            var text = $(".couponList .click-text")
            for(var i=0; i<elements.length; i++){
                var clip = new ZeroClipboard.Client();
                clip.setHandCursor( true );
                
                clip.addEventListener('load', function (client) {
                    debugstr("Flash movie loaded and ready.");
                });
                var newval = text[i].text;
                if(newval == undefined){
                    newval = text[i].innerHTML;
                }
                var newlink = buttons[i].href;

                var cb = function callback(someclip, sometext){
                    return function(client){
                        someclip.setText(sometext);
                    };
                };
                var my_complete = function(someurl){
                    return function(client){
                        window.open(someurl);
                    };
                };
                
                clip.addEventListener('mouseOver', cb(clip, newval));
                clip.addEventListener('onComplete', my_complete(newlink) );
                clip.glue( buttons[i], container[i]);
                clips.push(clip);
            }
			//clip.glue( $('#l1sc'), $('#l1st') );
		}
    startZC();
				$('#matrix-products').dataTable( {
					"bPaginate": false,
					"bLengthChange": false,
					"bFilter": false,
					"bInfo": false,
                    "bSearch":false,
                    "aoColumns":[
                    null,
                    null,
                    null,
                    null,
                    {"sType":"tax"},
                    {"sType":"p"},
                    {"bSortable":false}
                    ],
                    "aaSorting":[[5,"asc"]],
					"bAutoWidth": false } );
        
});
</script>
</head>
