<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150127185354 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE AdvertiserTransaction ADD manual TINYINT(1) NOT NULL");
        $this->addSql("UPDATE AdvertiserTransaction SET manual = 1 WHERE merchant_id IS NULL");
        $this->addSql("UPDATE AdvertiserTransaction SET manual = 0 WHERE merchant_id IS NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE AdvertiserTransaction DROP manual");
    }
}
