<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151222192343 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Merchant ADD category_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Merchant ADD CONSTRAINT FK_8DDD47B712469DE2 FOREIGN KEY (category_id) REFERENCES Category (id)");
        $this->addSql("CREATE INDEX IDX_8DDD47B712469DE2 ON Merchant (category_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Merchant DROP FOREIGN KEY FK_8DDD47B712469DE2");
        $this->addSql("DROP TABLE Category");
        $this->addSql("DROP INDEX IDX_8DDD47B712469DE2 ON Merchant");
        $this->addSql("ALTER TABLE Merchant DROP category_id");
    }
}
