<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20151119174117 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("SET FOREIGN_KEY_CHECKS = 0");
        $this->addSql("ALTER TABLE Merchant ADD popshopsId INT NOT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL");
        $this->addSql("UPDATE Merchant SET popshopsId = id");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_8DDD47B74EE0B28E ON Merchant (popshopsId)");
        $this->addSql("ALTER TABLE Network ADD popshopsId INT NOT NULL, CHANGE id id INT AUTO_INCREMENT NOT NULL");
        $this->addSql("UPDATE Network SET popshopsId = id");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_AF39BE204EE0B28E ON Network (popshopsId)");
        $this->addSql("SET FOREIGN_KEY_CHECKS = 1");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("SET FOREIGN_KEY_CHECKS = 0");
        $this->addSql("DROP INDEX UNIQ_8DDD47B74EE0B28E ON Merchant");
        $this->addSql("ALTER TABLE Merchant DROP popshopsId, CHANGE id id INT NOT NULL");
        $this->addSql("DROP INDEX UNIQ_AF39BE204EE0B28E ON Network");
        $this->addSql("ALTER TABLE Network DROP popshopsId, CHANGE id id INT NOT NULL");
        $this->addSql("SET FOREIGN_KEY_CHECKS = 1");
    }
}
