<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140717160356 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE user CHANGE charity_id charity_id INT DEFAULT NULL");
        $this->addSql("UPDATE user SET charity_id = NULL WHERE charity_id NOT IN (SELECT id FROM Charity)");
        $this->addSql("ALTER TABLE user ADD CONSTRAINT FK_8D93D649F5C97E37 FOREIGN KEY (charity_id) REFERENCES Charity (id)");
        $this->addSql("CREATE INDEX IDX_8D93D649F5C97E37 ON user (charity_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE user DROP FOREIGN KEY FK_8D93D649F5C97E37");
        $this->addSql("DROP INDEX IDX_8D93D649F5C97E37 ON user");
        $this->addSql("ALTER TABLE user CHANGE charity_id charity_id INT NOT NULL");
        $this->addSql("UPDATE user SET charity_id = 0 WHERE charity_id IS NULL");
    }
}
