<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140719145715 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE INDEX IDX_B58A56DC4D232B29 ON Payable (registeredAt)");
        $this->addSql("CREATE INDEX IDX_8D93D649B23DB7B8 ON user (created)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP INDEX IDX_B58A56DC4D232B29 ON Payable");
        $this->addSql("DROP INDEX IDX_8D93D649B23DB7B8 ON user");
    }
}
