<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140724130655 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE AdvertiserTransaction DROP INDEX IDX_F0E93BC622808A0B, ADD UNIQUE INDEX UNIQ_F0E93BC622808A0B (cashback_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE AdvertiserTransaction DROP INDEX UNIQ_F0E93BC622808A0B, ADD INDEX IDX_F0E93BC622808A0B (cashback_id)");
    }
}
