<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140723161834 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Payment (id INT AUTO_INCREMENT NOT NULL, user_id INT DEFAULT NULL, amount NUMERIC(10, 2) NOT NULL, requestedAt DATETIME NOT NULL, paidAt DATETIME DEFAULT NULL, status VARCHAR(20) NOT NULL, INDEX IDX_A295BD91A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE Payment ADD CONSTRAINT FK_A295BD91A76ED395 FOREIGN KEY (user_id) REFERENCES user (uid)");
        $this->addSql("ALTER TABLE Payable ADD payment_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Payable ADD CONSTRAINT FK_B58A56DC4C3A3BB FOREIGN KEY (payment_id) REFERENCES Payment (id)");
        $this->addSql("CREATE INDEX IDX_B58A56DC4C3A3BB ON Payable (payment_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Payable DROP FOREIGN KEY FK_B58A56DC4C3A3BB");
        $this->addSql("DROP TABLE Payment");
        $this->addSql("DROP INDEX IDX_B58A56DC4C3A3BB ON Payable");
        $this->addSql("ALTER TABLE Payable DROP payment_id");
    }
}
