<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140721191000 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE user CHANGE payment_method payment_method VARCHAR(255) DEFAULT NULL, CHANGE paypal_email paypal_email VARCHAR(250) DEFAULT NULL, CHANGE last_login last_login DATETIME DEFAULT NULL, CHANGE last_refer last_refer DATETIME DEFAULT NULL, CHANGE created created DATETIME DEFAULT NULL, CHANGE fb_access_token fb_access_token VARCHAR(255) DEFAULT NULL, CHANGE twitter_token_secret twitter_token_secret VARCHAR(255) DEFAULT NULL, CHANGE twitter_access_token twitter_access_token VARCHAR(255) DEFAULT NULL, CHANGE last_cashback last_cashback DATETIME DEFAULT NULL");
        $this->addSql("UPDATE user SET facebook_auto = 0 WHERE facebook_auto = ''");
        $this->addSql("UPDATE user SET twitter_auto = 0 WHERE twitter_auto = ''");
        $this->addSql("UPDATE user SET payment_method = NULL WHERE payment_method = ''");
        $this->addSql("UPDATE user SET paypal_email = NULL WHERE paypal_email = ''");
        $this->addSql("UPDATE user SET last_login = NULL WHERE last_login = '' OR last_login = '0000-00-00 00:00:00'");
        $this->addSql("UPDATE user SET last_refer = NULL WHERE last_refer = '' OR last_refer = '0000-00-00 00:00:00'");
        $this->addSql("UPDATE user SET last_cashback = NULL WHERE last_cashback = '' OR last_cashback = '0000-00-00 00:00:00'");
        $this->addSql("UPDATE user SET created = NULL WHERE created = '' OR created = '0000-00-00 00:00:00'");
        $this->addSql("UPDATE user SET alias = CONCAT('U', uid) WHERE alias = ''");
        $this->addSql("UPDATE user SET admin = 0 WHERE admin = ''");
        $this->addSql("UPDATE user SET send_reminders = 0 WHERE send_reminders = ''");
        $this->addSql("UPDATE user SET send_updates = 0 WHERE send_updates = ''");
        $this->addSql("UPDATE user SET fb_access_token = NULL WHERE fb_access_token = ''");
        $this->addSql("UPDATE user SET twitter_token_secret = NULL WHERE twitter_token_secret = ''");
        $this->addSql("UPDATE user SET twitter_access_token = NULL WHERE twitter_access_token = ''");
        $this->addSql("UPDATE user SET purchase_exempt = 0 WHERE purchase_exempt = ''");
        $this->addSql("UPDATE user SET email_refer_info = 0 WHERE email_refer_info = ''");
        $this->addSql("UPDATE user SET email_83 = 0 WHERE email_83 = ''");
        $this->addSql("UPDATE user SET email_60 = 0 WHERE email_60 = ''");
        $this->addSql("UPDATE user SET raw_data = NULL WHERE raw_data = ''");
        $this->addSql("UPDATE user SET raw_user_data = NULL WHERE raw_user_data = ''");
        $this->addSql("UPDATE user SET last_sync = NULL WHERE last_sync = '' OR last_sync = '0000-00-00 00:00:00'");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE user CHANGE payment_method payment_method VARCHAR(255) NOT NULL, CHANGE paypal_email paypal_email VARCHAR(250) NOT NULL, CHANGE last_login last_login DATETIME NOT NULL, CHANGE last_refer last_refer DATETIME NOT NULL, CHANGE created created DATETIME NOT NULL, CHANGE fb_access_token fb_access_token VARCHAR(255) NOT NULL, CHANGE twitter_token_secret twitter_token_secret VARCHAR(255) NOT NULL, CHANGE twitter_access_token twitter_access_token VARCHAR(255) NOT NULL, CHANGE last_cashback last_cashback DATETIME NOT NULL");
    }
}
