<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140717153332 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $this->addSql(<<<SQL
INSERT INTO Charity (name, id) VALUES
("American Heart Association", 9),
("American Red Cross", 1),
("Animal Welfare Institute", 12),
("Big Brothers Big Sisters of America", 15),
("Boys & Girls Club of America", 3),
("CARE", 16),
("Catholic Charities USA", 17),
("Cystic Fibrosis Foundation", 13),
("Disabled American Veterans", 18),
("Feed The Children", 19),
("Feeding America", 14),
("Friends of Long Beach Animals", 29),
("Green Wish", 28),
("Habitat for Humanity International", 5),
("Humane Society of the U.S.", 20),
("Leukemia & Lymphoma Society", 21),
("Nature Conservancy", 6),
("Salvation Army", 8),
("Save The Children", 22),
("Special Olympics", 23),
("UNCF", 25),
("UNICEF", 7),
("United Jewish Communities", 26),
("World Vision", 27)
SQL
        );
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        $this->addSql('TRUNCATE TABLE Charity');
    }
}
