<?php

namespace DoctrineMigrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20140805135449 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE Payable ADD isExtrabux TINYINT(1) NOT NULL");

        // early versions of Referral where registeredAt is null
        $this->addSql("UPDATE Payable SET registeredAt = STR_TO_DATE(month, '%Y%m') WHERE payableType = 'referral' AND month IS NOT NULL");
        $this->addSql("UPDATE Payable SET availableAt = DATE_ADD(registeredAt, INTERVAL 90 DAY) WHERE payableType = 'referral' AND availableAt IS NULL AND month IS NOT NULL");

        // any entry without registeredAt were imports from Extrabux
        $this->addSql("UPDATE Payable SET isExtrabux = 1 WHERE registeredAt IS NULL");
        $this->addSql("UPDATE Payable SET isExtrabux = 0 WHERE registeredAt IS NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $this->addSql("ALTER TABLE Payable DROP isExtrabux");
    }
}
