
<html xml:lang="en" xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta name="generator" content="HTML Tidy for Linux (vers 6 November 2007), see www.w3.org" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
<meta name="description" content="Save money on millions of products from thousands of top online stores at BeeSavy.com with comparison shopping, cash back, and coupons." />
<title>BeeSavy – Taking the sting out of online shopping</title>
<link rel="shortcut icon" href="/images/favicon.ico" />
<link href="/styles/account.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/main.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/home.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/results.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/view.css" media="screen" rel="stylesheet" type="text/css" />
<link href="/styles/button.css" media="screen" rel="stylesheet" type="text/css" />
<link rel="stylesheet" type="text/css" media="all" href="/scroll/styles/jScrollPane.css" />
<link rel="stylesheet" type="text/css" media="all" href="/scroll/styles/scrollstyles.css" />
<link media="screen" rel="stylesheet" href="/styles/colorbox.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script src="/colorbox/jquery.colorbox.js"></script>
<!-- Generated by OpenX 2.8.7 -->
<!-- <script type='text/javascript' src='http://50.16.95.24/openx/www/delivery/spcjs.php?id=1'></script>-->
<script type="text/javascript" src="/script_files/ZeroClipboard.js"></script>
<script type='text/javascript' src='/script_files/nav_bar.js'></script>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23342317-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script type='text/javascript'>
$(document).ready(function(){
    $(".make-home").colorbox();
});
</script>
</head>
