<html xml:lang='en' xmlns='http://www.w3.org/1999/xhtml' lang='en'>
<head>
<meta name='generator' content='HTML Tidy for Linux (vers 6 November 2007), see www.w3.org' />
<link rel="shortcut icon" href="/images/favicon.ico" />
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<meta http-equiv='content-type' content='text/html; charset=ISO-8859-1'>
<meta name='description' content='Save money on millions of products from thousands of top online stores at BeeSavy.com with comparison shopping, cash back, and coupons.' />
<title>BeeSavy – Taking the sting out of online shopping</title>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-23342317-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<!-- Generated by OpenX 2.8.7 -->
<!-- <script type='text/javascript' src='http://50.16.95.24/openx/www/delivery/spcjs.php?id=1'></script> -->
<script type="text/javascript">
if (document.images)
{
 // create object

var i=0;
    // set image list
images = new Array();
imageObj1 = new Image();
   imageObj1.src="../images/btn-compare-prices.gif";
   imageObj2 = new Image();
   imageObj2.src="../images/btn-compare-pricesR.gif"
   imageObj3 = new Image();
   imageObj3.src="../images/shopbystoreBt.gif"
   imageObj4 = new Image();
   imageObj4.src="../images/shopbystoreBtR.gif"
   imageObj5 = new Image();
   imageObj5.src= "../images/FindCouponsBt.gif"
   imageObj6 = new Image();
   imageObj6.src= "../images/FindCouponsBtR.gif"
   imageObj7 = new Image();
   imageObj7.src= "../images/ClickToCopyCodeBt.gif"
   imageObj8 = new Image();
   imageObj8.src= "../images/ClickToCopyCodeBtR.gif"
   imageObj9 = new Image();
   imageObj9.src= "../images/CashBackBtR.gif"
   imageObj10 = new Image();
   imageObj10.src= "../images/CashBackBt.gif"
   imageObj11 = new Image();
   imageObj11.src= "../images/ShopNowBtR.gif"
   imageObj12 = new Image();
   imageObj12.src="../images/ShopNowBt.gif"
   imageObj13 = new Image();
   imageObj13.src="../images/ShopNowBtR.gif"
   imageObj14 = new Image();
   imageObj14.src= "../images/ShopNowBt.gif"
   imageObj15 = new Image();
   imageObj15.src="../images/ShopCashBackBtR.gif"
   imageObj16 = new Image();
   imageObj16.src="../images/ShopCashBackBt.gif"
   imageObj17 = new Image();
   imageObj17.src= "../images/BtnSaveChangesBg.gif"
   imageObj18 = new Image();
   imageObj18.src="../images/BtnSaveChangesRBg.gif"
   imageObj19 = new Image();
   imageObj19.src="../images/BtnLogIn.gif"
   imageObj20 = new Image();
   imageObj20.src="../images/BtnLogInR.gif"
   imageObj21 = new Image();
   imageObj21.src="../images/BtnSignUp.gif"
   imageObj22 = new Image();
   imageObj22.src="../images/BtnSignUpR.gif"
   imageObj23 = new Image();
   imageObj23.src="../images/BtnSlideSignUp.gif"
   imageObj24 = new Image();
   imageObj24.src="../images/BtnSlideSignUpR.gif"
   imageObj25 = new Image();
   imageObj25.src="../images/BtnSendMessage.gif"
   imageObj26 = new Image();
   imageObj26.src="../images/BtnSendMessageR.gif"
   imageObj27 = new Image();
   imageObj27.src="../images/BtnStartSaving.gif"
   imageObj28 = new Image();
   imageObj28.src="../images/BtnStartSavingR.gif"
   imageObj29 = new Image();
   imageObj29.src="../images/BtnSendPassword.gif"
   imageObj30 = new Image();
   imageObj30.src="../images/BtnSendPasswordR.gif"
   imageObj31 = new Image();
   imageObj31.src="../images/BtnRequestBg.gif"
   imageObj32 = new Image();
   imageObj32.src="../images/BtnRequestRBg.gif"
   imageObj33 = new Image();
   imageObj33.src="../images/BtnRequestGrayBg.gif"
   imageObj34 = new Image();
   imageObj34.src="../images/BtnRequestGrayRBg.gif"
   imageObj35 = new Image();
   imageObj35.src="../images/BtnPreviewBg.gif"
   imageObj36 = new Image();
   imageObj36.src="../images/BtnPreviewRBg.gif"
   imageObj37 = new Image();
   imageObj37.src="../images/BtnGetStartedBg.gif"
   imageObj38 = new Image();
   imageObj38.src="../images/BtnGetStartedRBg.gif"
   imageObj39 = new Image();
   imageObj39.src="../images/BtnPreviewBg.gif"
   imageObj40 = new Image();
   imageObj40.src="../images/BtnPreviewRBg.gif"
   imageObj41 = new Image();
   imageObj41.src="../images/BtnGrayBg.gif"
}
</script>
<link rel="shortcut icon" href="images/favicon.ico" />
<link href='/styles/pagination.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/main.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/home.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/results.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/button.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/account.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/deals.css' media='screen' rel='stylesheet' type='text/css' />
<link href='/styles/shopping.css' media='screen' rel='stylesheet' type='text/css' />
<link rel='stylesheet' type='text/css' media='all' href='/scroll/styles/jScrollPane.css' />
<link rel='stylesheet' type='text/css' media='all' href='/scroll/styles/scrollstyles.css' />
<link media="screen" rel="stylesheet" href="/styles/colorbox.css" />
<script type='text/javascript' src="https://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>
<script type='text/javascript' src="/colorbox/jquery.colorbox.js"></script>
<script type='text/javascript' src='/script_files/nav_bar.js'></script>
<?php if($this->router->class == "product"){?>
    <script type="text/javascript" src="/scroll/scripts/jquery.mousewheel.js"></script>
    <script type="text/javascript" src="/scroll/scripts/jScrollPane.js"></script>
    <script type="text/javascript" src="/script_files/jquery.pagination.js"></script>
    <link rel="stylesheet" type="text/css" media="all" href="/scroll/styles/jScrollPane.css" />
    <link rel="stylesheet" type="text/css" media="all" href="/scroll/styles/scrollstyles.css" />
    <script>
        $(function() {
            // this initialises the demo scollpanes on the page.
             $('#pane1').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
            $('#pane2').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
        }); 
    </script> 
<?php }?>
<?php if($this->router->class == "stores"){?>
<script type="text/javascript" src="/scroll/scripts/jquery.mousewheel.js"></script>
<script type="text/javascript" src="/scroll/scripts/jScrollPane.js"></script>
<script type="text/javascript" src="/scroll/scripts/jScrollPane.js"></script>
<script type="text/javascript" src="/script_files/jquery.pagination.js"></script>


<script>
    $(function() {
        // this initialises the demo scollpanes on the page.
         $('#pane1').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
        $('#pane2').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
    }); 
</script> 

<link rel="stylesheet" type="text/css" media="all" href="scroll-styles/jScrollPane.css" />

<script>
    $(function() {
        // this initialises the demo scollpanes on the page.
         $('#pane1').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
        $('#pane2').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
    }); 
</script> 
<?php }?>
<?php if($this->router->class == "coupon"){?>
<script type="text/javascript" src="/scroll/scripts/jquery.mousewheel.js"></script>
<script type="text/javascript" src="/scroll/scripts/jScrollPane.js"></script>
<script type="text/javascript" src="/script_files/jquery.pagination.js"></script>
<script type="text/javascript" src="/zeroclipboard/ZeroClipboard.js">
</script>
<script>
    $(function() {
        // this initialises the demo scollpanes on the page.
         $('#pane1').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
        $('#pane2').jScrollPane({ showArrows: true, scrollbarWidth: 15, arrowSize: 16 });
        ZeroClipboard.setMoviePath('<? echo base_url() ?>zeroclipboard/ZeroClipboard.swf');
		var clips = [];
		
		function startZC() {
            var elements = $(".couponList");
            var container = $(".couponList .click-contain");
            var buttons = $(".couponList .click-button");
            var text = $(".couponList .click-text")
            for(var i=0; i<elements.length; i++){
                var clip = new ZeroClipboard.Client();
                clip.setHandCursor( true );
                
                clip.addEventListener('load', function (client) {
                    debugstr("Flash movie loaded and ready.");
                });
                var newval = text[i].text;
                if(newval == undefined){
                    newval = text[i].innerHTML;
                }
                var newlink = buttons[i].href;

                var cb = function callback(someclip, sometext){
                    return function(client){
                        someclip.setText(sometext);
                    };
                };
                var my_complete = function(someurl){
                    return function(client){
                        window.open(someurl);
                    };
                };
                
                clip.addEventListener('mouseOver', cb(clip, newval));
                clip.addEventListener('onComplete', my_complete(newlink) );
                clip.glue( buttons[i], container[i]);
                clips.push(clip);
            }
			//clip.glue( $('#l1sc'), $('#l1st') );
		}
    startZC();
    }); 
</script> 

<script type="text/javascript">
var _gaq = _gaq || [];
_gaq.push(['_setAccount', 'UA-4329126-1']);
_gaq.push(['_setCustomVar', 5, 'Member', 81230, 3]);
_gaq.push(['_trackPageview']);
(function() {
    var ga = document.createElement('script');
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    ga.setAttribute('async', 'true');
    document.documentElement.firstChild.appendChild(ga);
})();
</script><script async src="/images/ga.js"></script>
<?php }?>
<?php if($this->router->class == "stores"){?>
<?php }?>
<script type='text/javascript'>
$(document).ready(function(){
    $(".make-home").colorbox();
});
</script>
<script>
$(document).ready(function() {
    $("div.SaveChanges").mouseover(function () {
        var element = $(this);
 		element.find('.BtnSaveChangesBg').addClass('BtnSaveChangesRBg').removeClass('BtnSaveChangesBg');
    }).mouseout(function () {
    	var element = $(this);
		element.find('.BtnSaveChangesRBg').addClass('BtnSaveChangesBg').removeClass('BtnSaveChangesRBg');
    });
	
    $("div.Request").mouseover(function () {
        var element = $(this);
 		element.find('.BtnRequestBg').addClass('BtnRequestRBg').removeClass('BtnRequestBg');
    }).mouseout(function () {
    	var element = $(this);
		element.find('.BtnRequestRBg').addClass('BtnRequestBg').removeClass('BtnRequestRBg');
    });
			
	    $("div.ShopByStore").mouseover(function () {
        var element = $(this);
		element.find('.nav-ShopByStore-Bt').addClass('BtnSBSOrangeRBg').removeClass('BtnSBSOrangeBg');
    }).mouseout(function () {
    	var element = $(this);
		element.find('.nav-ShopByStore-Bt').addClass('BtnSBSOrangeBg').removeClass('BtnSBSOrangeRBg');
    });
	
	    $("div.FindCoupons").mouseover(function () {
        var element = $(this);
		element.find('.nav-FindCoupons-Bt').addClass('BtnFCOrangeRBg').removeClass('BtnFCOrangeBg');
    }).mouseout(function () {
    	var element = $(this);
		element.find('.nav-FindCoupons-Bt').addClass('BtnFCOrangeBg').removeClass('BtnFCOrangeRBg');
    });
	});
</script>
</head>
